
package City_nursing_hospital.Interfaces;


import City_nursing_hospital.services.Manager;
import java.awt.Color;
import java.awt.Font;
import javax.swing.plaf.basic.BasicInternalFrameUI;


public class addcashier extends javax.swing.JInternalFrame {
    
    
    public addcashier() {
        initComponents();
        
        this.setBorder(null);
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
        
         // Load patient data from file into the JTable
        loadCashierData();
        
        jTable1.getTableHeader().setFont(new Font("segoe UI", Font.BOLD, 10));
        jTable1.getTableHeader().setOpaque(false);
        jTable1.getTableHeader().setBackground(new Color(225,225,255));
        jTable1.getTableHeader().setForeground(new Color(51,153,255));
        jTable1.setRowHeight(25);
    }
    
    private void loadCashierData() {
    // Get the manager instance (assuming you have a way to access it)
    Manager manager = new Manager(); // Adjust based on how you manage instances

    // Call the method in the Manager class to load cashier data
    manager.loadCashierData(jTable1); // Pass JTable for updating
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        editjButton2 = new javax.swing.JButton();
        deletecashierjButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        passjTextField1 = new javax.swing.JTextField();
        numjTextField5 = new javax.swing.JTextField();
        emailjTextField3 = new javax.swing.JTextField();
        namejTextField2 = new javax.swing.JTextField();
        idjTextField1 = new javax.swing.JTextField();
        addjButton1 = new javax.swing.JButton();
        addjButton2 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(710, 410));
        setMinimumSize(new java.awt.Dimension(710, 410));
        setPreferredSize(new java.awt.Dimension(710, 410));

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(710, 410));
        jPanel1.setMinimumSize(new java.awt.Dimension(705, 410));
        jPanel1.setPreferredSize(new java.awt.Dimension(710, 410));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "E-mail", "Number"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setSelectionBackground(new java.awt.Color(255, 51, 51));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(70);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(70);
            jTable1.getColumnModel().getColumn(2).setMinWidth(150);
            jTable1.getColumnModel().getColumn(2).setMaxWidth(150);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 6, 450, 315));

        editjButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/City_nursing_images/edit-text.png"))); // NOI18N
        editjButton2.setText("Edit");
        editjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editjButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(editjButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, -1, -1));

        deletecashierjButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/City_nursing_images/trash.png"))); // NOI18N
        deletecashierjButton3.setText("Delete");
        deletecashierjButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletecashierjButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(deletecashierjButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, -1, -1));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 216, -1, -1));

        jPanel2.setBackground(new java.awt.Color(51, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Add Cashier", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bookman Old Style", 1, 18))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        jLabel2.setText("Employee ID:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 45, -1, -1));

        jLabel3.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        jLabel3.setText("Username:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 88, -1, -1));

        jLabel4.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        jLabel4.setText("E-mail:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 122, -1, -1));

        jLabel5.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        jLabel5.setText("Contact Number:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 153, -1, -1));

        jLabel7.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        jLabel7.setText("Password");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 189, -1, -1));

        passjTextField1.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        jPanel2.add(passjTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 186, 80, -1));

        numjTextField5.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        jPanel2.add(numjTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 150, 80, -1));

        emailjTextField3.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        jPanel2.add(emailjTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 122, 80, -1));

        namejTextField2.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        jPanel2.add(namejTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 85, 80, -1));

        idjTextField1.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        idjTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idjTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(idjTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 42, 60, -1));

        addjButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/City_nursing_images/diskette.png"))); // NOI18N
        addjButton1.setText("Add Cashier");
        addjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addjButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(addjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 238, -1, 29));

        addjButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/City_nursing_images/eraser.png"))); // NOI18N
        addjButton2.setText("Clear");
        addjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addjButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(addjButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 238, -1, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 220, 310));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void idjTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idjTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idjTextField1ActionPerformed

    private void addjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addjButton1ActionPerformed
        
     // Get the manager instance (assuming you have a way to access it)
    Manager manager = new Manager(); // Adjust based on how you manage instances

    String employeeId = idjTextField1.getText();
    String username = namejTextField2.getText();
    String email = emailjTextField3.getText();
    String contactNumber = numjTextField5.getText();
    String password = passjTextField1.getText();

    // Call the method in the Manager class
    manager.addCashier(employeeId, username, email, contactNumber, password, jTable1); // Pass JTable for updating
    
    }//GEN-LAST:event_addjButton1ActionPerformed

    private void editjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editjButton2ActionPerformed

    }//GEN-LAST:event_editjButton2ActionPerformed

    private void deletecashierjButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletecashierjButton3ActionPerformed
     // Get the manager instance (assuming you have a way to access it)
    Manager manager = new Manager(); // Adjust based on how you manage instances

    // Call the method in the Manager class to delete cashier details
    manager.deleteCashier(jTable1); // Pass JTable for updating
    }//GEN-LAST:event_deletecashierjButton3ActionPerformed

    private void addjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addjButton2ActionPerformed
        // Clear all input fields
        idjTextField1.setText(" ");
        namejTextField2.setText("");
        emailjTextField3.setText(" ");
        numjTextField5.setText("");

        
    }//GEN-LAST:event_addjButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addjButton1;
    private javax.swing.JButton addjButton2;
    private javax.swing.JButton deletecashierjButton3;
    private javax.swing.JButton editjButton2;
    private javax.swing.JTextField emailjTextField3;
    private javax.swing.JTextField idjTextField1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField namejTextField2;
    private javax.swing.JTextField numjTextField5;
    private javax.swing.JTextField passjTextField1;
    // End of variables declaration//GEN-END:variables
}
