package City_nursing_hospital.Interfaces;


import City_nursing_hospital.services.HospitalService;
import City_nursing_hospital.services.Manager;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.Date;
import javax.swing.plaf.basic.BasicInternalFrameUI;



public class addpatient extends javax.swing.JInternalFrame {
    
    private static int lastPatientId = 0;
    private static final String FILE_NAME = "patients.txt";
    

    public addpatient() {
        initComponents();
        
        this.setBorder(null);
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);

        // Initialize patient ID
        initializePatientId();

        // Generate the next patient ID and display it
        idjTextField1.setText(generatePatientId());
  
    }
    
    private void initializePatientId() {
        try (BufferedReader reader = new BufferedReader(new FileReader(FILE_NAME))) {
            String line;
            while ((line = reader.readLine()) != null) {
                if (line.startsWith("Patient ID: ")) {
                    int id = Integer.parseInt(line.substring("Patient ID: ".length()).replaceAll("\\D", ""));
                    if (id > lastPatientId) {
                        lastPatientId = id;
                    }
                }
            }
        } catch (IOException e) {
            // File not found or error reading file, initialize ID to 0
            lastPatientId = 0;
        }
    }
    
    private String generatePatientId() {
        lastPatientId++;
        return String.format("CHN%03d", lastPatientId);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        idjLabel2 = new javax.swing.JLabel();
        idjTextField1 = new javax.swing.JTextField();
        namejLabel3 = new javax.swing.JLabel();
        namejTextField2 = new javax.swing.JTextField();
        agejLabel4 = new javax.swing.JLabel();
        agejTextField3 = new javax.swing.JTextField();
        nicjLabel3 = new javax.swing.JLabel();
        nicTextField2 = new javax.swing.JTextField();
        numjLabel6 = new javax.swing.JLabel();
        numjTextField5 = new javax.swing.JTextField();
        datejLabel7 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        categoryjLabel8 = new javax.swing.JLabel();
        categoryjComboBox1 = new javax.swing.JComboBox<>();
        docjLabel10 = new javax.swing.JLabel();
        specialistComboBox = new javax.swing.JComboBox<>();
        addjButton3 = new javax.swing.JButton();
        addjButton2 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(710, 410));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Add Patient", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bookman Old Style", 1, 24))); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(650, 404));

        idjLabel2.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        idjLabel2.setText("Patient ID:");

        idjTextField1.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        idjTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idjTextField1ActionPerformed(evt);
            }
        });

        namejLabel3.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        namejLabel3.setText("Patient Name:");

        namejTextField2.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N

        agejLabel4.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        agejLabel4.setText("Age:");

        agejTextField3.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N

        nicjLabel3.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        nicjLabel3.setText("NIC:");

        nicTextField2.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        nicTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nicTextField2ActionPerformed(evt);
            }
        });

        numjLabel6.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        numjLabel6.setText("Contact Number");

        numjTextField5.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        numjTextField5.setPreferredSize(new java.awt.Dimension(70, 24));

        datejLabel7.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        datejLabel7.setText("Appiment Date:");

        jDateChooser1.setDateFormatString("dd-MM-yyyy");
        jDateChooser1.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jDateChooser1.setMinimumSize(new java.awt.Dimension(12, 12));
        jDateChooser1.setPreferredSize(new java.awt.Dimension(22, 22));

        categoryjLabel8.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        categoryjLabel8.setText("Category:");

        categoryjComboBox1.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        categoryjComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "General", "Emergency", "Maternity", "Pediatric" }));

        docjLabel10.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        docjLabel10.setText("specilist:");

        specialistComboBox.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        specialistComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dr. Smith", "Dr. John", "Dr. Lee", "Dr. Brown" }));

        addjButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/City_nursing_images/diskette.png"))); // NOI18N
        addjButton3.setText("Add Patient");
        addjButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addjButton3ActionPerformed(evt);
            }
        });

        addjButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/City_nursing_images/eraser.png"))); // NOI18N
        addjButton2.setText("Clear");
        addjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addjButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(426, 426, 426)
                        .addComponent(addjButton3)
                        .addGap(18, 18, 18)
                        .addComponent(addjButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(categoryjComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(categoryjLabel8))
                                .addGap(62, 62, 62)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(docjLabel10)
                                    .addComponent(specialistComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(idjLabel2)
                                    .addComponent(nicjLabel3)
                                    .addComponent(nicTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(62, 62, 62)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(numjLabel6)
                                    .addComponent(numjTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(namejTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(namejLabel3))
                                .addGap(59, 59, 59)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(datejLabel7)
                                    .addComponent(agejTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(agejLabel4))))))
                .addGap(0, 41, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idjLabel2)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(namejLabel3)
                        .addComponent(agejLabel4)))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(namejTextField2)
                    .addComponent(agejTextField3)
                    .addComponent(idjTextField1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numjLabel6)
                            .addComponent(datejLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(numjTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(nicjLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nicTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(categoryjLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(docjLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(categoryjComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(specialistComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addjButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addjButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idjTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idjTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idjTextField1ActionPerformed

    private void addjButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addjButton3ActionPerformed
    String newPatientId = idjTextField1.getText();
    String name = namejTextField2.getText();
    String ageStr = agejTextField3.getText();
    String nic = nicTextField2.getText();
    String contactNumber = numjTextField5.getText();
    Date appointmentDate = jDateChooser1.getDate(); // Get appointment date from date chooser
    String category = categoryjComboBox1.getSelectedItem().toString();
    String specialist = specialistComboBox.getSelectedItem().toString();

    // Assume you have a reference to a Manager or Cashier
    HospitalService hospitalService = new Manager(); // or new Cashier(); based on the context

    // Call addPatient method from HospitalService
    hospitalService.addPatient(newPatientId, name, ageStr, nic, contactNumber, appointmentDate, category, specialist);

    // Clear fields after adding the patient
    clearFields();
}

    // Method to clear input fields
    private void clearFields() {
    idjTextField1.setText("");
    namejTextField2.setText("");
    agejTextField3.setText("");
    nicTextField2.setText("");
    numjTextField5.setText("");
    jDateChooser1.setDate(null);
    categoryjComboBox1.setSelectedIndex(0);
    specialistComboBox.setSelectedIndex(0);
    
    }//GEN-LAST:event_addjButton3ActionPerformed

    private void nicTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nicTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nicTextField2ActionPerformed

    private void addjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addjButton2ActionPerformed
        clearFields();
    }//GEN-LAST:event_addjButton2ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addjButton2;
    private javax.swing.JButton addjButton3;
    private javax.swing.JLabel agejLabel4;
    private javax.swing.JTextField agejTextField3;
    private javax.swing.JComboBox<String> categoryjComboBox1;
    private javax.swing.JLabel categoryjLabel8;
    private javax.swing.JLabel datejLabel7;
    private javax.swing.JLabel docjLabel10;
    private javax.swing.JLabel idjLabel2;
    private javax.swing.JTextField idjTextField1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel namejLabel3;
    private javax.swing.JTextField namejTextField2;
    private javax.swing.JTextField nicTextField2;
    private javax.swing.JLabel nicjLabel3;
    private javax.swing.JLabel numjLabel6;
    private javax.swing.JTextField numjTextField5;
    private javax.swing.JComboBox<String> specialistComboBox;
    // End of variables declaration//GEN-END:variables
}
