
package City_nursing_hospital.Interfaces;

import City_nursing_hospital.Interfaces.cashierGUI;
import javax.swing.JOptionPane;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;


public class cashier_loginGUI extends javax.swing.JFrame {
    
    private int loginAttempts = 0; // Counter for login attempts
    private final int MAX_ATTEMPTS = 3; // Maximum number of login attempts

    /**
     * Creates new form cashier_loginGUI
     */
    public cashier_loginGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        loginjButton1 = new javax.swing.JButton();
        namejTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        backgroundimge1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/City_nursing_images/cashier (1).png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 120, 120));

        jLabel2.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel2.setText("Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        jLabel1.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel1.setText("Username");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 28, -1, 30));

        loginjButton1.setBackground(new java.awt.Color(54, 70, 78));
        loginjButton1.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        loginjButton1.setForeground(new java.awt.Color(255, 255, 255));
        loginjButton1.setText("Login");
        loginjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginjButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(loginjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, -1, 30));

        namejTextField1.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        getContentPane().add(namejTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 110, -1));

        jPasswordField1.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 110, -1));

        backgroundimge1.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        backgroundimge1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/City_nursing_images/Blue and White Medical and Health Care Banner (1).jpg"))); // NOI18N
        getContentPane().add(backgroundimge1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 130));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginjButton1ActionPerformed
       
        String username = namejTextField1.getText();
        String password = new String(jPasswordField1.getPassword());

        // Validate login credentials
        boolean isValid = validateCredentials(username, password);

        if (isValid) {
            JOptionPane.showMessageDialog(this, "Login Successful! Welcome, " + username + "!");
            java.awt.EventQueue.invokeLater(new Runnable() {
                @Override
                public void run() {
                    cashierGUI cashdash = new cashierGUI();
                    cashdash.adminname.setText(username);
                    cashdash.setVisible(true);
                }
            });
            this.dispose(); // Close the login frame
        } else {
            loginAttempts++; // Increment the login attempt count

            // Check if the user has exceeded maximum login attempts
            if (loginAttempts < MAX_ATTEMPTS) {
                int remainingAttempts = MAX_ATTEMPTS - loginAttempts;
                JOptionPane.showMessageDialog(this, "Login Failed. You have " + remainingAttempts + " more attempt(s).");
            } else {
                JOptionPane.showMessageDialog(this, "You have exceeded the maximum login attempts. The system will now exit.");
                System.exit(0); // Exit the application after exceeding max attempts
            }
        }             
    }//GEN-LAST:event_loginjButton1ActionPerformed

   

    private boolean validateCredentials(String username, String password) {
        boolean usernameFound = false;

        try (BufferedReader reader = new BufferedReader(new FileReader("cashiers.txt"))) {
            String line;
            while ((line = reader.readLine()) != null) {
                // Check for the username
                if (line.startsWith("Username:")) {
                    if (line.substring("Username:".length()).trim().equals(username)) {
                        usernameFound = true;
                    } else {
                        usernameFound = false;
                    }
                }

                // Check for the password
                if (usernameFound && line.startsWith("Password:")) {
                    if (line.substring("Password:".length()).trim().equals(password)) {
                        return true;
                    }
                    // If the password is not matched, reset usernameFound
                    usernameFound = false;
                }
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error reading file.");
        }
        return false;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cashier_loginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cashier_loginGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundimge1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JButton loginjButton1;
    private javax.swing.JTextField namejTextField1;
    // End of variables declaration//GEN-END:variables
}
