/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package City_nursing_hospital.Interfaces;

import City_nursing_hospital.Interfaces.homeGUI;
import javax.swing.JOptionPane;

/**
 *
 * @author Hp
 */
public class loadingGUI extends javax.swing.JFrame {

    /**
     * Creates new form loadingGUI
     */
    public loadingGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundjPanel1 = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        hospital = new javax.swing.JLabel();
        doclogo = new javax.swing.JLabel();
        lodinglabel = new javax.swing.JLabel();
        precentagelabel = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        backgroundimage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backgroundjPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name.setFont(new java.awt.Font("Sitka Text", 1, 48)); // NOI18N
        name.setText("CITY NURSING HOME");
        backgroundjPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, -1, -1));

        hospital.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        hospital.setText("H O S P I T A L");
        backgroundjPanel1.add(hospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, -1, -1));

        doclogo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        doclogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/City_nursing_images/pngegg (2)-fotor-bg-remover-20240821211514.png"))); // NOI18N
        backgroundjPanel1.add(doclogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 520, 400));

        lodinglabel.setFont(new java.awt.Font("Sitka Banner", 0, 18)); // NOI18N
        lodinglabel.setForeground(new java.awt.Color(51, 102, 255));
        lodinglabel.setText("Loading...");
        backgroundjPanel1.add(lodinglabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 280, -1));

        precentagelabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        precentagelabel.setForeground(new java.awt.Color(51, 102, 255));
        precentagelabel.setText("0 %");
        backgroundjPanel1.add(precentagelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 410, 100, 20));

        jProgressBar1.setForeground(new java.awt.Color(51, 204, 255));
        backgroundjPanel1.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 440, 920, 20));

        backgroundimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/City_nursing_images/Blue and White Medical and Health Care Banner (1).jpg"))); // NOI18N
        backgroundjPanel1.add(backgroundimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundjPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundjPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loadingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loadingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loadingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loadingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        loadingGUI ld = new loadingGUI();
        ld.setVisible(true);
        
        try {
             
             for(int i=0; i<=100;i++)
             {
                Thread.sleep(100);
                ld.precentagelabel.setText(i +"%");
                
                if(i==10)
                {
                   ld.lodinglabel.setText("Turning On Modules..");
                }
                if(i==20)
                {
                   ld.lodinglabel.setText("Loading Modules..");
                }
                if(i==50)
                {
                   ld.lodinglabel.setText("Connecting to Database..");
                }
                if(i==80)
                {
                   ld.lodinglabel.setText("Connection Successful!");
                }
                ld.jProgressBar1.setValue(i);
                 
             }
             
             homeGUI home = new homeGUI();  
             home.setVisible(true);   
             home.setLocationRelativeTo(null);  //open home GUI center of the screen
             ld.dispose();  
             
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundimage;
    private javax.swing.JPanel backgroundjPanel1;
    private javax.swing.JLabel doclogo;
    private javax.swing.JLabel hospital;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel lodinglabel;
    private javax.swing.JLabel name;
    private javax.swing.JLabel precentagelabel;
    // End of variables declaration//GEN-END:variables
}
